ALTER TABLE vouchers
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN start_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN end_at SET DEFAULT CURRENT_TIMESTAMP;