-- =========================================================
-- V5: Fix BCrypt password hash cho admin và user
-- Hash được generate trực tiếp bởi Spring BCryptPasswordEncoder (cost=10)
-- admin / admin123
-- user  / user123
-- =========================================================

-- BCrypt hash của "admin123" - generated by Spring BCryptPasswordEncoder
UPDATE users
SET password    = '$2a$10$BHRoYv9VYEPCX8rTQKbbUuoLCDSo0YoxXfUSeqPXRGr3PCdo6Oh9a',
    updated_at  = SYSDATETIME()
WHERE username  = N'admin';

-- BCrypt hash của "user123" - generated by Spring BCryptPasswordEncoder
UPDATE users
SET password    = '$2a$10$OLzwARbxuyxyJKbcjuErJOzXyjhHmvQNrL6z/K.3vd5Sv4R1bOx3S',
    updated_at  = SYSDATETIME()
WHERE username  = N'user';
